server:
  port: 8201

spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: 
    application:
       name: springcloud-dept-config-dev-client
eureka:  
  client:
    service-url:  
      defaultZone: http://eureka8761.com:8761/eureka/
    
---
server:
  port: 8202
  
spring:
  profiles:
    active:
      - test
---
spring:
  profiles: 
    application: 
       name: springcloud-dept-config-test-client
eureka:  
  client:
    service-url:  
      defaultZone: http://eureka8761.com:8761/eureka/

       

   
  