spring:
  profiles:
    active:
      - test
---
spring:
  profiles: 
    application:
       name: springcloud-dept-config-test
---
spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: 
    application:
       name: springcloud-dept-config-dev